# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=uttamsharma
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
# 'update' will automatically create/modify tables based on your Java classes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Application Settings
server.port=8080
app.base-url=http://localhost:8080/api/v1/urls